language: csharp
solution: Ametista.sln
install:
  - nuget restore ./src/Ametista.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./src/Ametista.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./src/Ametista.UnitTest/bin/Release/Ametista.UnitTest.dll
